/**
 * create at 07/12/19
 */


const APP_ROOT = 'MYAPP'

// mine
const MINE = 'MINE'
/// test
const MINE_TEST_REDUCE_COUNT = `${APP_ROOT}_${MINE}_TEST_REDUCE_COUNT`
const MINE_TEST_LOADING_DATA = `${APP_ROOT}_${MINE}_TEST_LOADING_DATA`
const MINE_TEST_LOADING_SUCCESS = `${APP_ROOT}_${MINE}_TEST_LOADING_SUCCESS`
const MINE_TEST_LOADING_FAIL = `${APP_ROOT}_${MINE}_TEST_LOADING_FAIL`


export {
  MINE_TEST_REDUCE_COUNT, 
  MINE_TEST_LOADING_DATA, 
  MINE_TEST_LOADING_SUCCESS, 
  MINE_TEST_LOADING_FAIL,
}

